plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.greysoft'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework:spring-webflux:6.2.8'  // For WebClient
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

	implementation 'org.postgresql:postgresql'  // PostgreSQL JDBC Driver
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Swagger OpenAPI Documentation
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.4.0'

	// Reactor Netty for WebClient (needed since no Zeebe/Camunda brings it)
	implementation 'io.projectreactor.netty:reactor-netty-http'

	// jBPM / KIE API for WorkItemHandler support
	implementation 'org.kie:kie-api:7.74.0.Final'
	implementation 'org.jbpm:jbpm-flow:7.74.0.Final'
}

tasks.named('test') {
	useJUnitPlatform()
}
